- README.md
- equinix/README.md
- equinix/ipxe-install
- equinix/userdata-create.yaml
- equinix/userdata-join.yaml
- general/README.md
- general/config-create.yaml
- general/config-join.yaml
- general/ipxe-create
- general/ipxe-join
The PR refactors repo https://github.com/bk201/hvst-ipxe/ according to some suggestions.
> Add examples for general case and Equinix Metal

- vagrant-pxe-harvester/ansible/roles/dhcp/tasks/main.yml
- vagrant-pxe-harvester/ansible/roles/http/tasks/main.yml
- vagrant-pxe-harvester/settings.yml
We should always test against the dev branch by default as the APIs
are constantly changing. Also make sure we update apt cache before installing
packages.
> use the ISO from master branch for testing by default

- equinix/README.md
- equinix/ipxe-install
- equinix/userdata-join.yaml
- general/README.md
- general/config-join.yaml
- general/ipxe-create
- general/ipxe-join
Update general and Equinix examples for HarvesterOS.
> Update general and Equinix examples for HarvesterOS

- vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
- vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
- vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
- vagrant-pxe-harvester/settings.yml
Add the required VIP parameters.
> Support VIP

- general/config-create.yaml
> general: add VIP example

- equinix/README.md
- equinix/ipxe-install
- general/ipxe-create
- general/ipxe-join
- vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-create.j2
- vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-join.j2
Adapt the changes in https://github.com/harvester/harvester-installer/pull/118
> Update net.ifnames parameters

- vagrant-pxe-harvester/setup_harvester.sh
setup_harvester.sh should return the RC from ansible-playbook so it
truly reflects the overall result.
> Exit with the proper RC

- equinix/README.md
- equinix/userdata-create.yaml
- equinix/userdata-join.yaml
- general/config-create.yaml
- general/config-join.yaml
Revive #22. The configurations of equinix and general need update as well.
> New config for NIC bonding

- vagrant-pxe-harvester/settings.yml
Adapt changes in https://github.com/harvester/harvester-installer/pull/145
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
> Update artifact URLs of master builds

- .gitignore
As those are ephemeral and temporary.
> Ignore all the .vagrant related artifacts

- vagrant-pxe-harvester/ansible/boot_harvester_node.yml
Adapt to the ingress change in the master head
> Update health check port

- equinix/userdata-create.yaml
- equinix/userdata-join.yaml
- general/config-create.yaml
- general/config-join.yaml
Related issue: https://github.com/harvester/harvester/issues/2119
> Add ntp_servers to general and equinix examples

- vagrant-pxe-harvester/settings.yml
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
Increase to 8 cores each node.
related: #53
> vagrant-pxe: increase CPU cores

- vagrant-pxe-harvester/settings.yml
> Increase default vCPU core count

- vagrant-pxe-harvester/settings.yml
Signed-off-by: Zespre Chang <zespre.chang@suse.com>
related: #56
> [backport v1.0] Increase the default disk size to 200GB

- README.md
- Update links to v1.0.x.
- Add license.
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
> README: Update links to previous versions

- vagrant-pxe-harvester/README.md
- vagrant-pxe-harvester/settings.yml
While trying to setup a Harvester environment using the Vagrant solution, i came across several issues that i want to improve with this issue to make it other users easier.
> Add more info to make life easier for users

- vagrant-pxe-airgap-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
- vagrant-pxe-airgap-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
- vagrant-pxe-airgap-harvester/settings.yml
- vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
- vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
- vagrant-pxe-harvester/settings.yml
- we support sftp configuration when installation.
make default that could be easier to transmit file
related to https://github.com/harvester/harvester-installer/pull/562
> ansiable: add sftp config

- vagrant-pxe-harvester/ansible/reinstall_rancher.yml
- vagrant-pxe-harvester/ansible/setup_harvester.yml
- vagrant-pxe-harvester/ansible/setup_rancher.yml
- vagrant-pxe-harvester/settings.yml
1.Replace rancher docker installation by helm
> Rancher installation using helm instead of docker

- vagrant-pxe-harvester/README.md
Steps to install and troubleshoot Vagrant installation on Tumbleweed.
> Document Vagrant installation on Tumbleweed

- vagrant-pxe-harvester/README.md
Adding Troubleshooting section to the Quick Start section in order to explain problem related with hanging installation when harvester files are missing.
Through this explanation user following the documentation can also find ways to debug it's own unique issues.
Due to connection issues the harvester files might now be pulled properly and the setup installation might hang and result in a broken state.
Added troubleshooting section how to pull files in that scenario and how to debug it. Providing with both ways to fix this issue and tools you can use to debug in order the installation hangs.
N/A
Documentation change; no test
Documentation added
> Add Troubleshooting section to Quick Start
