harvester/ipxe-examples

vagrant-pxe-harvester/Vagrantfile
vagrant-pxe-harvester/ansible/boot_harvester_node.yml
vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
vagrant-pxe-harvester/ansible/roles/harvester/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-join.j2
vagrant-pxe-harvester/settings.yml

To be able to test Harvester VM scheduling behavior (e.g. schedule
VMs on the nodes that has the available resource), we need to be able
to customize each node's CPU and memory so we can simulation various
resource utilization scenarios.

Enable customization of individual node settings

---

vagrant-pxe-harvester/ansible/boot_harvester_node.yml

Do not use `/v1-public/auth-modes` for endpoint readiness probe as the API
no longer exist. Use just the base endpoint instead.

Fix Harvester endpoint readiness probe

---

vagrant-pxe-harvester/ansible/boot_harvester_node.yml
vagrant-pxe-harvester/ansible/reinstall_harvester_node.yml
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-create.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-join.j2
vagrant-pxe-harvester/reinstall_harvester_node.sh
vagrant-pxe-harvester/settings.yml

It is needed to facilitate testing disaster recovery scenarios. This patch also update the playbooks to work with the new OS image.

Add capability to reinstall a single Harvester node + new OS updates

---

vagrant-pxe-harvester/ansible.cfg
vagrant-pxe-harvester/ansible/setup_pxe_server.yml

There's no need to run all the plays in escalated privilege. We should only
escalate when needed.

Fix ansible privilege escalation

---

vagrant-pxe-harvester/README.md

Fix a typo in the README of vagrant example.

Fix typo in README

---

vagrant-pxe-harvester/ansible/roles/harvester/tasks/_download_media.yml
vagrant-pxe-harvester/ansible/roles/harvester/tasks/main.yml

Renaming downloaded media files to the fixed name, then we can use arbitrary URI string in `settings.yml`
This will only affect to `ipxe-example`.
The example of `v.0.3.0-preview1`:
```yml
harvester_iso_url: https://releases.rancher.com/harvester/v0.3.0-preview1/harvester-v0.3.0-preview1-amd64.iso
harvester_kernel_url: https://releases.rancher.com/harvester/v0.3.0-preview1/harvester-v0.3.0-preview1-vmlinuz-amd64
harvester_ramdisk_url: https://releases.rancher.com/harvester/v0.3.0-preview1/harvester-v0.3.0-preview1-initrd-amd64
```
those files will be renamed to
```yml
harvester_iso_url: harvester-amd64.iso
harvester_kernel_url: harvester-vmlinuz-amd64
harvester_ramdisk_url: harvester-initrd-amd64
```

Renaming media files to fixed name

---

vagrant-pxe-harvester/README.md
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/settings.yml

With the latest networking changes (1), user must first find out
the name of the NICs to enable, then enable them accordingly.
This PR enables user to configure the NICs in settings.yml.
Notice that the NIC names maybe different from server to server.
1. https://github.com/harvester/harvester-installer/pull/118

Allow NIC to be configurable

---

vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2

If you were testing VIP's `static mode`, you should base on this to retest.

Fix the template didnt get configured vip mode

---

vagrant-pxe-harvester/ansible/boot_harvester_node.yml
vagrant-pxe-harvester/ansible/roles/harvester/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-create.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-join.j2
vagrant-pxe-harvester/settings.yml

Rootfs media seem to be release-specific so it should be configurable,
just as the rest of the release media.

Allow rootfs URL to be configurable

---

vagrant-pxe-harvester/Vagrantfile

This can cause issues if the extra unused NIC is not enabled at boot.

Remove extra NIC

---

vagrant-pxe-harvester/ansible/roles/harvester/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-create.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-join.j2

Using ip=dhcp is not recommended when there are more than one DHCP networks.
The behavior of `ip=dhcp` is not stable. The VM has 3 interfaces:
- `ens5`: `libvirt-vagrant` network
- `ens6`: `harvester` network. IPs are allocated according to MACs.
- `ens7`: also `harvester` network. IPs are also allocated if request.
If we use `ip=dhcp` parameter, In initramfs stage, the Dracut module tries to get IPs from all interfaces. The result is not stable, sometimes `ens5` and `ens6` get IPs. Sometimes only `ens7` get IPs. We should use a fixed one.

Specify DHCP interface

---

vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/settings.yml

The VM disk size is also increased because we need to allocate a 50G
volume (thin-provisioned) for Prometheus data.
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

Switch to bonding management network

---

vagrant-pxe-harvester/Vagrantfile
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2

- Use e1000 NIC model
- virtio-net doesn't play well with bonding device even there
is only one bonding slave.
- Use virtio disk to improve disk performance.

Specify NIC model and virtio disks

---

vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/settings.yml

issue: https://github.com/harvester/harvester/issues/1535
Check whether we can get `timesync` on each node after installation. Also, please check whether `SystemNTPServers` is same as settings in yml.
```
> timedatectl show-timesync
SystemNTPServers=0.suse.pool.ntp.org 1.suse.pool.ntp.org
FallbackNTPServers=0.suse.pool.ntp.org 1.suse.pool.ntp.org 2.suse.pool.ntp.org 3.suse.pool.ntp.org
ServerName=0.suse.pool.ntp.org
ServerAddress=111.235.248.121
RootDistanceMaxUSec=5s
PollIntervalMinUSec=32s
PollIntervalMaxUSec=34min 8s
PollIntervalUSec=34min 8s
NTPMessage={ Leap=0, Version=4, Mode=4, Stratum=1, Precision=-19, RootDelay=0, RootDispersion=1.525ms, Reference=PPS, OriginateTimestamp=Thu 2021-11-11 07:22:45 UTC, ReceiveTimestamp=Thu 2021-11-11 07:22:45 UTC, TransmitTimestamp=Thu 2021-11-11 …
```

feat(vagrant-ipx-harvester): add default ntp servers

---

vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2

Use dev harvester-mgmt via 192.168.0.1
Resolves the following issues:
1. Harvester is broken after enabling vlan network on bond0(https://github.com/harvester/harvester/issues/1541).
2. When enabling vlan network on harvester-mgmt and create a VM using a single vlan NIC. It cannot access the internet because default route is missing.

Update default route

---

vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/proxy/files/default
vagrant-pxe-harvester/ansible/roles/proxy/handlers/main.yml
vagrant-pxe-harvester/ansible/roles/proxy/tasks/main.yml
vagrant-pxe-harvester/ansible/setup_pxe_server.yml
vagrant-pxe-harvester/settings.yml

When `offline` is enabled, external services are not routable by default.
An HTTP proxy is set up in DHCP node(http://192.168.0.254:3128).
This helps to simulate and test an air-gapped environment with an HTTP proxy.

Add offline option

---

vagrant-pxe-harvester/ansible/roles/https/files/https
vagrant-pxe-harvester/ansible/roles/https/files/self-signed.conf
vagrant-pxe-harvester/ansible/roles/https/files/ssl-params.conf
vagrant-pxe-harvester/ansible/roles/https/handlers/main.yml
vagrant-pxe-harvester/ansible/roles/https/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/https/templates/openssl.conf.j2
vagrant-pxe-harvester/ansible/setup_pxe_server.yml
vagrant-pxe-harvester/settings.yml

add new role **https** to _pxe-server_ with self-signed cert, key will be printed in console.
related feature:  https://github.com/harvester/harvester/issues/1260
preview:

add self-signed CA for https

---

vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2

as the issue https://github.com/harvester/harvester/issues/1521 , make joining node to use **VIP** in `server_url` would be more stable.

change  to use VIP on `server_url`

---

vagrant-pxe-harvester/ansible/roles/https/files/https
vagrant-pxe-harvester/ansible/roles/https/files/self-signed.conf
vagrant-pxe-harvester/ansible/roles/https/files/ssl-params.conf
vagrant-pxe-harvester/ansible/roles/https/handlers/main.yml
vagrant-pxe-harvester/ansible/roles/https/meta/main.yaml
vagrant-pxe-harvester/ansible/roles/https/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/https/templates/openssl.conf.j2
vagrant-pxe-harvester/ansible/setup_pxe_server.yml
vagrant-pxe-harvester/settings.yml

Renaming handler in https to resolve naming conflict.
new `restart nginx` will not be skipped in `https: false` condition.

renew for #36

---

general/ipxe-create
general/ipxe-join

Add kernel parameter `rd.net.dhcp.retry=3` for an unstable DHCP environment. See https://github.com/harvester/harvester/issues/1363

Add rd.net.dhcp.retry kernel parameter

---

vagrant-pxe-harvester/settings.yml

We are using more resources now and have started to see out-of-CPU errors.
Here is some observation from my new-created 4-node cluster:
Node1:
```
Resource                       Requests      Limits
--------                       --------      ------
cpu                            6210m (77%)   8750m (109%)
memory                         7216Mi (45%)  9548Mi (59%)
```
Node2:
```
Resource                       Requests      Limits
--------                       --------      ------
cpu                            3850m (64%)   3150m (52%)
memory                         3630Mi (30%)  2616Mi (21%)
```
Node3:
```
Resource                       Requests      Limits
--------                       --------      ------
cpu                            3490m (58%)   2950m (49%)
memory …
```

vagrant-pxe: increase CPU cores

---

vagrant-pxe-harvester/settings.yml

Signed-off-by: Zespre Chang <zespre.chang@suse.com>
200GB disk per node is more suitable for upgrade testing purposes as suggested [here](https://github.com/harvester/harvester/pull/3035#discussion_r1004540788)

Increase the default disk size to 200GB

---

equinix/ipxe-install

PR  changes the install script to use the GH artifact kernel/initrd artifacts available post v1.1.2-rc3 for boot strapping nodes.
Related to: https://github.com/harvester/harvester/issues/2226

[v1.1.2] GH kernel and initrd artifacts

---

vagrant-pxe-airgap-harvester/settings.yml
vagrant-pxe-harvester/settings.yml

**Problem:**
The installation disk minimum requirement already increased to 250Gi, we need to increase disk size in Vagrant config
**Solution:**
Increase default Harvester disk size to 250Gi.
**Related issue:**
https://github.com/harvester/harvester/issues/3842

Increase default Harvester disk size to 250Gi.

---

vagrant-pxe-airgap-harvester/settings.yml
vagrant-pxe-harvester/settings.yml

Related issue: https://github.com/harvester/harvester/issues/4210
Due to the previous design, the persistent partition is only 59G in size. It's quite easy to trigger kubelet image collection during an upgrade (too small to contain two releases' images at the same time)
Change the disk size to 500G to make the testing more smooth. In this case, the partition will grow to 90G.

Vagrant: increase default disk size to 500G

---

vagrant-pxe-airgap-harvester/ansible/setup_pxe_server.yml
vagrant-pxe-harvester/ansible/setup_pxe_server.yml

When harvester_network_config.dhcp_server.https is set to false, ansible gets a bit confused and doesn't run the "restart nginx" handler when deploying the pxe_server.  This can be seen if you manually run `vagrant up pxe_server`:
```
RUNNING HANDLER [http : restart nginx] *****************************************
skipping: [pxe_server] => changed=false
false_condition: settings['harvester_network_config']['dhcp_server']['https']
skip_reason: Conditional result was False
```
The problem with this is that if nginx isn't restarted, the newly added default site config isn't read and the "wait for PXE server HTTP port to get ready" task in the Setup Harvester playbook never succeeds.
I think what's happening is that with the http role appearing before the https role, the http role by itself …

vagrant: pxe_server: apply https role before http

---

vagrant-pxe-airgap-harvester/ansible/roles/https/meta/main.yaml
vagrant-pxe-harvester/ansible/roles/https/meta/main.yaml

- Make sure we do not overwrite the same handler
I saw a similar CI error on the Jenkins.
That is the same issue mentioned on https://github.com/harvester/ipxe-examples/pull/67.
I thought the `dependencies` role might have some different mechanism.
Adding the condition and changing the loading order would make Jenkins and my local environment happy.
Or could we revert this commit and make `http`/`https` have their restart nginx handler? (That will be simpler.)
commit: https://github.com/harvester/ipxe-examples/commit/1b83fcc8345b4332df05ecc7a2d538ef0da4ce61
Related PR: https://github.com/harvester/ipxe-examples/pull/39

ansible: add condition for dependencies role

---

vagrant-pxe-airgap-harvester/ansible/prepare_harvester_nodes.yml
vagrant-pxe-airgap-harvester/ansible/reinstall_harvester_node.yml
vagrant-pxe-airgap-harvester/ansible/roles/harvester/tasks/main.yml
vagrant-pxe-airgap-harvester/ansible/setup_harvester.yml
vagrant-pxe-harvester/ansible/reinstall_harvester_node.yml
vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
vagrant-pxe-harvester/ansible/roles/harvester/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/settings.yml

This PR creates a new entry for both DNS on the harvester node as well as defining it in the DHCP scope for the virtual cluster. I also updated the `include` to `include_tasks` in ansible since those were deprecated.

Add DNS support and update include to include_tasks

---

vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
vagrant-pxe-harvester/reinstall_harvester_node.sh

1. Preparing complete DHCP mapping
* Fix problem in previous PR #69  that adding node will have wrong address due to incomplete dhcp mapping.
1. DHCP server contains complete nodes info :ballot_box_with_check: 
```
vagrant@pxe-server:~$ cat /etc/dhcp/dhcpd.conf 
...
host harvest_vip {
hardware ethernet 02:00:00:03:3D:61;
fixed-address 192.168.0.131;
}
host harvest_node_0 {
hardware ethernet 02:00:00:0D:62:E2;
fixed-address 192.168.0.30;
server-name "harvester-node-0";
}
host harvest_node_1 {
hardware ethernet 02:00:00:35:86:92;
fixed-address 192.168.0.31;
server-name "harvester-node-1";
}
host harvest_node_2 {
hardware ethernet 02:00:00:2F:F2:2A;
fixed-address 192.168.0.32;
server-name "harvester-node-2";
}
host harvest_node_3 {
hardware ethernet 02:00:00:A7:E6:FF;
fixed-address …
```

Fix incomplete DHCP mapping

---

vagrant-pxe-airgap-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/settings.yml

- now we can change the `etcd_only: true` to make this node
an etcd-only node. (This is for witness feature)

vagrant: support etcd only nodes

---

equinix/README.md
equinix/ipxe-install
general/ipxe-create
general/ipxe-join
vagrant-pxe-airgap-harvester/ansible/roles/harvester/templates/ipxe-create.j2
vagrant-pxe-airgap-harvester/ansible/roles/harvester/templates/ipxe-join.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-create.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-join.j2

This will be necessary once we merge
https://github.com/harvester/harvester-installer/pull/636 as the preflight checks will fail when run under virtualization, or with limited hardware resources.

Add harvester.install.skipchecks=true

---

vagrant-pxe-harvester/Vagrantfile

The settings option `rancher_config.enabled` is not used in the `Vagrantfile`, thus the Rancher node is always deployed, even if it is not enabled.

Respect the config option `rancher_config.enabled`

---

vagrant-pxe-harvester/ansible/setup_harvester.yml

To fix the following error:
```
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.
```

ansible: use include_tasks instead built.include

---

vagrant-pxe-harvester/ansible/setup_rancher.yml

... because this has been deprecated in Ansible 2.11 and removed in 2.14.
Related to: https://github.com/harvester/harvester/issues/5411

Remove `warn` option from shell module

---

vagrant-pxe-harvester/settings.yml

The DNS server 4.4.2.2 actually doesn't exist.  This causes problems, notably when deploying RKE2 clusters on openSUSE VMs in Harvester, because you end up with the following in your VM's /etc/resolv.conf:
```
nameserver 4.4.2.2
nameserver 192.168.0.254
nameserver 8.8.8.8
```
The resolver will try these servers in order when doing DNS lookups. Because 4.4.2.2 doesn't exist, and 192.168.0.254 also doesn't respond to DNS queries (it's only a DHCP server...) it means we can hit timeouts when rancher-system-agent tries to pull images, e.g.:
```
Jun 05 03:41:54 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T03:41:54Z" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.27.13-rke2r1"
Jun 05 03:42:23 rke2-v12713-pool1-996bce2c-5nds2 …
```

Use 1.1.1.1 as dns_server, instead of 4.4.2.2

---

vagrant-pxe-harvester/Vagrantfile
vagrant-pxe-harvester/ansible.cfg
vagrant-pxe-harvester/ansible/reinstall_rancher.yml
vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
vagrant-pxe-harvester/ansible/roles/harvester/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/ansible/setup_harvester.yml
vagrant-pxe-harvester/ansible/setup_rancher.yml
vagrant-pxe-harvester/settings.yml

1. Specify K3s version for Rancher by K3S channel instead of full verison
* In practice, we care about the K8s major and minor verion (e.g. `v1.29`, `v1.30`...) but seldom the patch version as it rolls quick.
* For convenient usage, leveraging `INSTALL_K3S_CHANNEL` env. variable instead of full `INSTALL_K3S_VERSION`.
* Reference
* https://docs.k3s.io/upgrades/manual
* https://github.com/k3s-io/k3s/blob/master/channel.yaml
1. Refactors
* Rename `vagrant_interface` to `vagrant_nic`
* Rename `mgmt_interface`/`mac` to `mgmt_nic`/`mgmt_mac`
* Move `sftp` from `harvester_network_config` to `harvester_config`
Issue harvester/harvester/issues/6972 was verified in the env. setup by this enhancement.

Specify Rancher's K3s platform by K3S_CHANNEL

---

vagrant-pxe-harvester/README.md

A note on how to prevent `zypper` from uninstalling Vagrant installed using `rpm -i` command.

Prevent zypper removing vagrant

---

vagrant-pxe-harvester/Vagrantfile
vagrant-pxe-harvester/ansible/setup_rancher.yml
vagrant-pxe-harvester/settings.yml

1. QEMU ovmf is not correct.
2. Rancher has new support matrix webpage
3. A Rancher `set-string` does not need to newer versions
1. Update ovmf to correct path
2. Update Rancher support matrix link
3. Drop old Rancher `set-string` 
n/a
Cluster can be provisioned correctly

Fix QEMU ovmf path and remove out-of-date rancher set-string

---

vagrant-pxe-harvester/Vagrantfile

In previous PR only handle ovmf file in OpenSUSE.
This PR checks paths for different OSes
```
ovmf_ubuntu = '/usr/share/qemu/OVMF.fd'
ovmf_opensuse = '/usr/share/qemu/ovmf-x86_64.bin'
if File.exist?(ovmf_ubuntu)
libvirt.loader = ovmf_ubuntu
libvirt.nic_model_type = 'e1000'
elsif File.exist?(ovmf_opensuse)
libvirt.loader = ovmf_opensuse
libvirt.nic_model_type = 'e1000'
end
```
* harvester/ipxe-examples/pull/90
manual
OK to provision a cluster

Config OVMF loader path for difference OS

---

vagrant-pxe-harvester/Vagrantfile
vagrant-pxe-harvester/ansible/roles/dhcp/templates/dhcpd.conf.j2
vagrant-pxe-harvester/ansible/roles/harvester/tasks/main.yml
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-create.j2
vagrant-pxe-harvester/ansible/roles/harvester/templates/ipxe-join.j2
vagrant-pxe-harvester/settings.yml

Enable Quemu guest agent and SSH access via `vagrant ssh` to Harvester nodes.
Remove Vagrant management network from Harvester nodes.
This change adds a virtual channel device for the Qemu guest agent to each Harvester node. Doing this enables Vagrant to accurately and quickly retrieve information about the running status of the Harvester nodes and manage the power state properly. In other words `vagrant status` works properly.
This change also adds SSH access information for Vagrant to allow users to gain SSH access to the Harvester nodes via `vagrant ssh`. This removes the need to configure the user's SSH keys in the settings - though that is still supported.
Lastly the Vagrant management network is removed from the Harvester nodes. This network is usually used by Vagrant to apply …

enable guest agent and ssh

---

vagrant-pxe-harvester/Vagrantfile
vagrant-pxe-harvester/ansible/roles/s3/tasks/main.yml
vagrant-pxe-harvester/ansible/setup_pxe_server.yml
vagrant-pxe-harvester/settings.yml

Add an S3 backup target to the PXE server.
For testing and developing backup related features, this makes the iPXE environment a little more convenient by making a Minio instance available on the PXE server.
When testing or developing backup related features (e.g. https://github.com/harvester/harvester/issues/7885) it may be necessary to have a working backup target available in the development environment.
In an iPXE development environment there is a dedicated VM for hosting services like the DHCP needed for PXE boot. When required, this VM should also host a Minio container, which can serve as an S3 backup target

Add S3 backup target
